services:
  app:
    build: .
    container_name: void_dispatch_app
    ports:
      - "11737:80"
    depends_on:
      - db
    volumes:
      - .:/var/www
      - ./env/.env:/var/www/.env

  db:
    image: mysql:5.7
    container_name: void_dispatch_db
    restart: always
    environment:
      MYSQL_DATABASE: void_dispatch
      MYSQL_ROOT_PASSWORD: mysql
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
